#!/usr/bin/env python
"""Generate CLI reference for the debug-scraper skill.

Extracts help text from kent and pdd CLIs and writes it to
.claude/skills/debug-scraper/cli-reference.md so the skill always
has an up-to-date view of available commands.

Usage:
    uv run python scripts/generate_cli_reference.py
    uv run python scripts/generate_cli_reference.py --check  # exit 1 if stale
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT = (
    REPO_ROOT / ".claude" / "skills" / "debug-scraper" / "cli-reference.md"
)


def run_help(cmd: list[str]) -> str:
    result = subprocess.run(
        ["uv", "run", *cmd, "--help"],
        capture_output=True,
        text=True,
        cwd=REPO_ROOT,
    )
    return result.stdout.strip()


def get_subcommands(cli: str) -> list[str]:
    """Parse subcommand names from a CLI's --help output."""
    help_text = run_help([cli])
    commands: list[str] = []
    in_commands = False
    for line in help_text.splitlines():
        if line.strip() == "Commands:":
            in_commands = True
            continue
        if in_commands:
            stripped = line.strip()
            if not stripped:
                break
            name = stripped.split()[0]
            commands.append(name)
    return commands


def generate() -> str:
    lines: list[str] = []
    lines.append(
        "<!-- AUTO-GENERATED by scripts/generate_cli_reference.py -->"
    )
    lines.append(
        "<!-- Do not edit manually. Run: uv run python scripts/generate_cli_reference.py -->"
    )
    lines.append("")

    # kent CLI
    lines.append("# kent CLI Reference")
    lines.append("")
    lines.append("```")
    lines.append(run_help(["kent"]))
    lines.append("```")
    lines.append("")

    for sub in get_subcommands("kent"):
        lines.append(f"## kent {sub}")
        lines.append("")
        lines.append("```")
        lines.append(run_help(["kent", sub]))
        lines.append("```")
        lines.append("")

    # pdd CLI
    lines.append("# pdd CLI Reference")
    lines.append("")
    lines.append("```")
    lines.append(run_help(["pdd"]))
    lines.append("```")
    lines.append("")

    for sub in get_subcommands("pdd"):
        help_text = run_help(["pdd", sub])
        lines.append(f"## pdd {sub}")
        lines.append("")
        lines.append("```")
        lines.append(help_text)
        lines.append("```")
        lines.append("")

        # Check for nested subcommands
        nested = []
        in_commands = False
        for line in help_text.splitlines():
            if line.strip() == "Commands:":
                in_commands = True
                continue
            if in_commands:
                stripped = line.strip()
                if not stripped:
                    break
                name = stripped.split()[0]
                nested.append(name)

        for nested_sub in nested:
            lines.append(f"### pdd {sub} {nested_sub}")
            lines.append("")
            lines.append("```")
            lines.append(run_help(["pdd", sub, nested_sub]))
            lines.append("```")
            lines.append("")

    return "\n".join(lines)


def main() -> None:
    content = generate()

    if "--check" in sys.argv:
        if not OUTPUT.exists():
            print(
                f"FAIL: {OUTPUT} does not exist. Run: uv run python scripts/generate_cli_reference.py"
            )
            sys.exit(1)
        existing = OUTPUT.read_text()
        if existing != content:
            print(
                f"FAIL: {OUTPUT} is out of date. Run: uv run python scripts/generate_cli_reference.py"
            )
            sys.exit(1)
        print("OK: cli-reference.md is up to date.")
        sys.exit(0)

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(content)
    print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()
